---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
    driver:
      network:
      - ["forwarded_port", {guest: 80, host: 8181}]

suites:
  - name: default
    run_list:
      - recipe[glpi::default]
    attributes: {
      'glpi': {
        'mailcollector': {
          'test@contoso.com': {
            'host': '{mail.contoso.com:110/pop/ssl}INBOX',
            'login': 'test@contoso.com',
            'filesize_max': 10,
            'password': 'test'
          }
        }
      }
    }
